addSbtPlugin("org.scalameta"    %% "sbt-scalafmt"    % "2.5.2")
addSbtPlugin("org.typelevel"     % "sbt-tpolecat"    % "0.5.0")
addSbtPlugin("io.spray"          % "sbt-revolver"    % "0.10.0")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"    % """2.1.5""")
addSbtPlugin("io.chrisdavenport" % "sbt-http4s-grpc" % "0.0.4")
